#ifndef __main_frame__
#define __main_frame__

/**
@file
Subclass of MainFrameUI, which is generated by wxFormBuilder.
*/

#include "../components/ui/ui.h"

//// end generated include

/** Implementing MainFrameUI */
class MainFrame : public MainFrameUI
{
public:
	/** Constructor */
	MainFrame(wxWindow *parent);
	//// end generated class members
};

#endif // __main_frame__
