#ifndef __pack_list_panel__
#define __pack_list_panel__

/**
@file
Subclass of PackListPanelUI, which is generated by wxFormBuilder.
*/

#include "../ui/ui.h"
#include "pack_list_view_model.h"

//// end generated include

/** Implementing PackListPanelUI */
class PackListPanel : public PackListPanelUI
{
public:
	/** Constructor */
	PackListPanel(wxWindow *parent);
	//// end generated class members
private:
	wxObjectDataPtr<PackListViewModel> m_pModel;
};

#endif // __pack_list_panel__
