#ifndef __pack_edit_panel__
#define __pack_edit_panel__

/**
@file
Subclass of PackPanelUI, which is generated by wxFormBuilder.
*/

#include "../ui/ui.h"

//// end generated include

/** Implementing PackPanelUI */
class PackEditPanel : public PackPanelUI
{
public:
	/** Constructor */
	PackEditPanel(wxWindow *parent);
	//// end generated class members
};

#endif // __pack_edit_panel__
